
export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const REGITER_USER_REQUEST = "REGITER_USER_REQUEST"
export const REGITER_USER_SUCCESS = "REGITER_USER_SUCCESS"
export const REGITER_USER_FAIL = "REGITER_USER_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERRORS"